In [1]:
import numpy as np


In [5]:
arr1=np.array([1, 2, 3, 4, 5,6])

In [6]:
print(arr1)
print(type(arr1))

[1 2 3 4 5 6]
<class 'numpy.ndarray'>


In [7]:
print(arr1.shape)

(6,)


In [8]:
arr1.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
arr2= np.array([[1,2,3,4,5,6],[2,3,4,5,6,7]])

In [13]:
arr2.shape

(2, 6)

In [14]:
a=np.arange(0,10,2)

In [15]:
a

array([0, 2, 4, 6, 8])

In [17]:
np.ones((3,4),dtype=int)

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [19]:
#identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [20]:
arr=np.array([[1,2,3],[4,5,6]])
print("Array :\n", arr)
print("Shape of array:", arr.shape)
print("Number od Dimensions",arr.ndim)
print("Data type:",arr.dtype)
print("Item size (in bytes)",arr.itemsize)

Array :
 [[1 2 3]
 [4 5 6]]
Shape of array: (2, 3)
Number od Dimensions 2
Data type: int64
Item size (in bytes) 8


In [21]:
## np array addition,subtraction,multiplication, division two arrays 
np1=np.array([1,2,3])
np2=np.array([4,5,6])
print("Addition:\n", np1 + np2)
print("Subtraction:\n", np1 - np2)
print("Multiplication:\n", np1 * np2)
print("Division:\n", np1 / np2)

Addition:
 [5 7 9]
Subtraction:
 [-3 -3 -3]
Multiplication:
 [ 4 10 18]
Division:
 [0.25 0.4  0.5 ]


In [25]:
## square root 
print(np.sqrt(np1))
print(np.exp(np2))
print(np.sin(np1))
print(np.log(np1))

[1.         1.41421356 1.73205081]
[ 54.59815003 148.4131591  403.42879349]
[0.84147098 0.90929743 0.14112001]
[0.         0.69314718 1.09861229]


In [26]:
## array slicing

In [27]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [28]:
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [31]:
arr[0:2,0:3]

array([[1, 2, 3],
       [4, 5, 6]])

In [32]:
arr[1:3,1:3]

array([[5, 6],
       [8, 9]])

In [33]:
arr[0,0]=100

In [34]:
arr

array([[100,   2,   3],
       [  4,   5,   6],
       [  7,   8,   9],
       [ 10,  11,  12]])

In [35]:
### statiscal concepts - Normalization

data=np.array([1,2,3,4,5])

In [38]:
mean=np.mean(data)
std_d=np.std(data)
data_normalized=(data-mean)/std_d

In [39]:
print(data_normalized)

[-1.41421356 -0.70710678  0.          0.70710678  1.41421356]


In [40]:
print(np.mean(data))
print(np.median(data))
print(np.std(data))
print(np.var(data))

3.0
3.0
1.4142135623730951
2.0


In [41]:
data>2

array([False, False,  True,  True,  True])

In [42]:
data[data>2]

array([3, 4, 5])

In [43]:
import pandas as pd
data = pd.Series([1, 2, 3, 4, 5])
